### ISSUE TITLE
Alias's not working even after following HowTo guide

### ISSUE THREAD

**Issue by The-Code-Monkey** [formium/tsdx#1034]
### Current Behavior

![image](https://user-images.githubusercontent.com/31218527/119134741-6fffcc00-ba35-11eb-926e-e7b50543556f.png)
![image](https://user-images.githubusercontent.com/31218527/119134762-755d1680-ba35-11eb-8a6d-f632ded6f4a6.png)
![image](https://user-images.githubusercontent.com/31218527/119134778-7a21ca80-ba35-11eb-879a-0984401b959e.png)

### Expected behavior

Should be able to alias

### Your environment

```text

System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Xeon(R) CPU
    Memory: 808.39 MB / 62.81 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
  npmPackages:
    tsdx: ^0.14.1 => 0.14.1 
    typescript: ^4.2.4 => 4.2.4 
  npmGlobalPackages:
    typescript: 4.2.4

```

**Comment by goldenjayr** [comment]
@The-Code-Monkey  why did you close this... have you found a solution?
