### ISSUE TITLE
please remove eslint-config-react-app from dependencies, it is required only for react projects

### ISSUE THREAD

**Issue by JustFly1984** [formium/tsdx#182]
```
warning "tsdx > eslint-config-react-app@5.0.1" has unmet peer dependency "babel-eslint@10.x".
warning "tsdx > eslint-config-react-app@5.0.1" has incorrect peer dependency "eslint-plugin-flowtype@3.x".
```

**Comment by JustFly1984** [comment]
also please update @typescript-eslint/eslint-plugin@1.13.0 to 2.0.0

**Comment by jaredpalmer** [comment]
Can you submit a PR?

**Comment by JustFly1984** [comment]
@jaredpalmer 
Which node version do you use to build? I will add `.nvmrc` to the project.

I'm running tests and getting an error:
<img width="731" alt="Screenshot 2019-08-22 03 50 30" src="https://user-images.githubusercontent.com/2255993/63477898-13523480-c490-11e9-8bdd-060eb8648b1c.png">

can't update stuff until you fix tests

**Comment by skvale** [comment]
- eslint-config-react-app is used for more than just React projects
- Bumping @typescript-eslint/eslint-plugin to 2.0.0 has breaking changes not supported by the current version of eslint-config-react-app
- The warning of unmet/incorrect peer dependencies are coming from here: https://github.com/facebook/create-react-app/blob/master/packages/eslint-config-react-app/package.json.  babel-eslint doesn't need to be a peer dependency for 100% TypeScript apps and it looks like eslint-plugin-flowtype could be `3.x || 4.x'

**Comment by JustFly1984** [comment]
@skvale have you tried to run tests?

**Comment by skvale** [comment]
It looks like the tests are passing from your screenshot

There is a noisy test for an invalid build: https://github.com/palmerhq/tsdx/blob/master/test/fixtures/build-invalid/src/index.ts

**Comment by skvale** [comment]
re:
> also please update @typescript-eslint/eslint-plugin@1.13.0 to 2.0.0

eslint-config-react-app just bumped their versions of typescript-eslint deps: https://github.com/facebook/create-react-app/pull/7540/files

tsdx could bump `eslint-config-react-app` and `@typescript-eslint/eslint-plugin` now

**Comment by JustFly1984** [comment]
it is better to dump sdx could bump eslint-config-react-app - it messes up linting projects without react

**Comment by agilgur5** [comment]
As was written previously above (https://github.com/formium/tsdx/issues/182#issuecomment-526948153), it's definitely not just for React projects -- can view [the rules and see for yourself](https://github.com/facebook/create-react-app/blob/d5c0fe287a6bc24c60ee52ca768bdf3a10b937e1/packages/eslint-config-react-app/index.js).

I'm not sure what "messes up linting projects without create-react-app" refers to. I'm open to changing to a different default ESLint config (I personally use Standard), however that's a separate story -- please propose an RFC if interested.
It would likely be a very breaking change and folks who use lint configs tend to not want to make stylistic choices themselves and so may be adverse to that. TSDX also has overlap with CRA / CRL users (and has a good bit of inspiration from CRA), so similar config is probably more consistent for those folks.

**Comment by JustFly1984** [comment]
@agilgur5 the issue for me is mostly out of date versions of dependencies in CRA. I use carefully managed list of eslint plugins myself, and would love to have smaller dependency tree, and less clutter in `npm i` logs about missing/outdated dependencies.

**Comment by agilgur5** [comment]
Ok, that's different from "messing up linting"; that would mean it works but just is outdated. #810 has this issue too. I suspect CRA has somewhat of the same issue as TSDX where a major bump in any sub-package causes a major in CRA so as a result you end up being slow to update dependencies as you batch them into majors.
In any case, I don't particularly want to maintain an ESLint config myself for reasons I've written in https://github.com/formium/tsdx/pull/890#issuecomment-703167625 . For ecosystem consistency also would prefer using an existing, well-used config. If you've got suggestions, feel free to make an RFC.
