### ISSUE TITLE
How can we use the StandardJS

### ISSUE THREAD

**Issue by woss** [formium/tsdx#761]
I see that we can customize the eslintrc but can we completely replace the linting process?
I'm using the [ts-standard ](https://github.com/toddbluhm/ts-standard) in the project.

**Comment by agilgur5** [comment]
> can we completely replace the linting process?

Sure, you don't have to use `tsdx lint` at all, so one can opt-out of it entirely. You'll want to update your `package.json.scripts.lint` command and potentially the pre-commit hook as well though.

For `ts-standard` though, one can just add [`eslint-config-standard-with-typescript`](https://github.com/standard/eslint-config-standard-with-typescript) though. One has to install all the plugins as well unfortunately. I do that myself as the VSCode integration of ESLint is much better maintained than the Standard one. 

Also @woss this is your second time filing an issue without using the issue template. Please do not remove the template, it is there for a reason.

**Comment by woss** [comment]
hi thanks for the answer but that was obvious. since I am new to this library I cannot possibly know will `yarn lint` break anything under the hood. 
thank you for the suggestions about ts-standard but I have pretty good setup already for listing. 


>Also @woss this is your second time filing an issue without using the issue template. Please do not remove the template, it is there for a reason. 

i didn't delete the template, I just clicked under the `suggested` templates `Don’t see your issue here? Open a blank issue.
` 
the https://github.com/formium/tsdx/issues/749  which 'template'  would you chose, bug? feature?

**Comment by woss** [comment]
also you just helped me make a decision on will I use this or not. for that I thank you

**Comment by agilgur5** [comment]
> hi thanks for the answer but that was obvious.

Er, ok, well that's what you asked about... If you had something more specific in mind, I would highly recommend you actually write about what specifically you mean and your use-case. I can't read minds and I have to spend _a lot_ more time interpreting questions with little-to-no details like #749

> since I am new to this library I cannot possibly know will `yarn lint` break anything under the hood.

That would've been quite helpful to mention in your opening comment. It does not as I said in my first comment.
The `lint` command is [quite small](https://github.com/formium/tsdx/blob/8b148cea34c1852f6fcf6e94a3758d7a9f46d9b2/src/index.ts#L573-L601) and most of the commands are independent of each other, so they can be replaced -- `build` is really the core of TSDX. With some commands TSDX may do more configuration for you out-of-the-box to have some parity with `build`, but TSDX actually doesn't have full parity everywhere yet and that configuration could be copied. #634 aims to further decouple the configuration out-of-core which would solve some issues and make that clearer I think.

> i didn't delete the template, I just clicked under the `suggested` templates `Don’t see your issue here? Open a blank issue. `

Ok, thanks for letting me know that. Will have to see if I can disable that.

> the #749 which 'template' would you chose, bug? feature?

One of the purposes of the issue template is also to make the author of the issue decide that. Are you asking for a new feature? Or do you think you've found a bug? Like I said, I don't really know what you were asking about in #749 so I can't tell you that. Based on your later response, it sounds like you were asking for an additional feature to be added to the templates.
