### ISSUE TITLE
Watch Mode not watching for changes.

### ISSUE THREAD

**Issue by yashguptaz** [formium/tsdx#782]
### Current Behavior
I created a fresh project with tsdx and used `yarn start`
In the terminal it says, `watching for changes`

But when I make any changes nothing happens.

![image](https://user-images.githubusercontent.com/36479718/88455758-b88e3d80-ce95-11ea-8d58-cc84d826037a.png)

### Expected behavior
I expected it to watch for change and compile my `dist`

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           |   0.13.2
| TypeScript       | 3.9.7
| Browser          | Microsoft Edge
| npm/Yarn         | yarn 1.19.0
| Node             | 12.18.2
| Operating System | Windows 10 - WSL2

**Comment by yashguptaz** [comment]
Seems like a WSL2 issue rather than a tsdx issue.
Closing this.
https://github.com/microsoft/WSL/issues/4417

**Comment by lizy0329** [comment]
Let the author know that this matter exists, are you sure that HRM does not need to be adjusted?

**Comment by yashguptaz** [comment]
yes, I referenced the WSL issue.
Everything is working fine now.

**Comment by lizy0329** [comment]
> yes, I referenced the WSL issue.
> Everything is working fine now.

You resolve this solution?
