### ISSUE TITLE
seems not support rollup format iife

### ISSUE THREAD

**Issue by Jogiter** [formium/tsdx#788]

**Comment by agilgur5** [comment]
Please don't remove the issue template, it is there for a reason.

### Features required

Yes I don't believe IIFE is supported if used. It wouldn't be that difficult to add though, we'd have to add it to the supported formats here: https://github.com/formium/tsdx/blob/5e5c3f804e68609083be978a080ab905dc7ec19d/src/createBuildConfigs.ts#L46-L89

as well as probably add some special cases into the Rollup config similar to the ones UMD has.

### Use-case?

To validate the use case for this feature request I was going to ask if UMD doesn't fit your use-case but based on the title change I guess the answer is yes, UMD can be used instead for your use case.

**Comment by StringKe** [comment]
Is there any temporary solution to support iife?

The generation method of umd is not perfect, and there are currently errors.

https://github.com/jaredpalmer/tsdx/issues/179#issuecomment-605502952
https://github.com/jaredpalmer/tsdx/issues/759
