### ISSUE TITLE
Output different folders with tsdx and tsconfig settings

### ISSUE THREAD

**Issue by alonfai** [formium/tsdx#791]
@agilgur5  Thanks for answering that. I found another issue relating to changing the output folder

I modify both the rollup `output` param and the tsconfig.json `outDir` and `declarationDir` to a parent folder of my project that is used for debugging my app that consumes the bundled output.

tsconfig.json

``` json
"compilerOptions": {
     "baseUrl": "./src",
      "outDir": "../../my-app/src/@scope/shared",
      "declarationDir": "../../my-app/src/@scope/shared"
      "allowJs": true,
      "alwaysStrict": true,
      "declaration": true,
      "esModuleInterop": true,
      "forceConsistentCasingInFileNames": true,
      "importHelpers": true,
      "jsx": "react",
      "lib": ["dom", "esnext"],
      "module": "esnext",
      "moduleResolution": "node",
      "noFallthroughCasesInSwitch": true,
      "noImplicitThis": true,
      "strictFunctionTypes": true,
      "strictPropertyInitialization": true,
      "strict": true,
      "allowSyntheticDefaultImports": true,
      "noUnusedParameters": false,
      "noUnusedLocals": false,
      "strictNullChecks": true,
      "noImplicitAny": false,
      "noEmit": true,
      "target": "es5",
      "sourceMap": true,
      "downlevelIteration": true
    }

```

tsdx.config.js

``` js

module.exports = {
  rollup(config, options) {
    return {
      ...config,
      // https://github.com/formium/tsdx/issues/213#issuecomment-540126058
      output: {
        ...config.output,
        // dir: path.join(__dirname, '../../my-app/src/@scope'),
        file: `../../my-app/src/@scope/shared/${path.basename(file)}`
      }
    }
    }
  }
};

```

The resulting run of tsdx build gives me the bundled esm/cjs for both development/production .js builds with the relevant typings, however I still have a `dist` folder under my scoped rollup project with the entry index.js file.

I attached a few pics to demonstrate the issue. 

// current tsdx/rollup project with a single index.js under `shared/dist folder

![Screen Shot 2020-08-10 at 4 03 13 pm](https://user-images.githubusercontent.com/11208491/89755495-0015fa00-db23-11ea-8f79-ce863ba18da0.png)

'use strict'

```js

if (process.env.NODE_ENV === 'production') {
  module.exports = require('./shared.cjs.production.min.js')
} else {
  module.exports = require('./shared.cjs.development.js')
}

```

// The other project that consumes the bundled output

![Screen Shot 2020-08-10 at 4 05 40 pm](https://user-images.githubusercontent.com/11208491/89755610-584cfc00-db23-11ea-83b9-2557d8f11670.png)

_Originally posted by @alonfai in https://github.com/formium/tsdx/issues/790#issuecomment-671178335_

**Comment by agilgur5** [comment]
Please don't remove issue templates, they are there for a reason. As I said in your other issue, this is another duplicate, this time of https://github.com/formium/tsdx/issues/351#issuecomment-657284291 . Please search the issues and read through docs before submitting issues.

<hr>
Also `outDir` is not currently supported by TSDX
