### ISSUE TITLE
Update rollup-plugin-terser dependency

### ISSUE THREAD

**Issue by known-as-bmf** [formium/tsdx#797]
### Current Behavior

[`rollup-plugin-terser` v5.x](https://github.com/formium/tsdx/blob/master/package.json#L91) has a [dependency on `serialize-javascript` 2.x](https://github.com/TrySound/rollup-plugin-terser/blob/bfd1391e49d537288ef09ba2247d316d263253d9/package.json#L37).
This version of `serialize-javascript` includes [an high severity security issue](https://github.com/advisories/GHSA-hxcc-f52p-wc94).

### Expected behavior

No security issue.

### Suggested solution(s)

Bump `rollup-plugin-terser` dependency to [at least `^6.0.0`](https://github.com/TrySound/rollup-plugin-terser/blob/49712e588d718c0c96c4aa4371948c2658a945e0/package.json#L31).

### Additional context

N/A

### Your environment

TSDX 0.13.2

**Comment by agilgur5** [comment]
Duplicate of https://github.com/formium/tsdx/pull/731#issuecomment-672246494
