### ISSUE TITLE
Rollup 2 support

### ISSUE THREAD

**Issue by cncolder** [formium/tsdx#821]
### Current Behavior

`tsdx` lock rollup@1.32.1 now

### Desired Behavior

Upgrade to rollup 2

### Suggested Solution

Release npm next tag `tsdx@next`

### Who does this impact? Who is this for?

Some plugins (e.g. [rollup-plugin-postcss](https://github.com/egoist/rollup-plugin-postcss)) has drop support rollup 1

**Comment by agilgur5** [comment]
Duplicate of #545
