### ISSUE TITLE
Add Preact’s bundle size GH action to all templates

### ISSUE THREAD

**Issue by jaredpalmer** [formium/tsdx#841]
Seems like everyone will want this https://github.com/preactjs/compressed-size-action

**Comment by agilgur5** [comment]
Duplicate of #496 / #741. And there's already a PR #705 that uses `size-limit` and adds commands and a GH action to the templates and has gone through some iterations (probably just about ready to merge).

@jaredpalmer would appreciate if you could also fill out the issue template and not make exceptions.
