### ISSUE TITLE
lint flag to make warnings exit with non-zero

### ISSUE THREAD

**Issue by georgevarghese185** [formium/tsdx#853]
### Current Behavior

If you have lint warnings and run `yarn lint` or `tsdx lint`, the warnings are printed but the command exits without an error

### Desired Behavior

It would be nice to have `tsdx lint` take a flag to exit with a non-zero code if warnings are found so that a pre-commit hook can prevent a commit from going through and require the user to fix the warnings.

### Who does this impact? Who is this for?

This is for people who want to force all lint errors _and_ warnings to be cleared before committing code.

**Comment by agilgur5** [comment]
ESLint has the `--max-warnings` flag, but it seems like there is no config option via `eslintrc` for this -- that would be optimal.

Without such a change upstream TSDX would need to forward the flag. Would prefer to forward _all_ flags to ESLint as we do with `tsdx test` and Jest but IIRC there's a limitation; had thought to do so some time ago

**Comment by agilgur5** [comment]
Ah, right, we use [ESLint's `CLIEngine` API](https://eslint.org/docs/developer-guide/nodejs-api#cliengine), which doesn't support all flags or converting all flags 😕 

That being said, `--max-warnings` would be fairly easy to implement in TSDX. Can use [`report.warningCount`](https://eslint.org/docs/developer-guide/nodejs-api#-lintresult-type) and add a small check after this line:

https://github.com/formium/tsdx/blob/116a043a221ef5a8d8dd3db0453c0b864fe3c368/src/index.ts#L597-L599
