### ISSUE TITLE
Make prettier config overridable

### ISSUE THREAD

**Issue by AndreaPontrandolfo** [formium/tsdx#856]
### Current Behavior

currently i can't edit/override the prettier config.

### Desired Behavior

I need to change the behaviour of the prettier formatting to better fit the needs of my projects.

### Suggested Solution

Make the prettier config overridable/extendable just like you did with the Eslint config

**Comment by agilgur5** [comment]
It should be configurable, [the templates generate a config](https://github.com/formium/tsdx/blob/08a8ef807cd708c1b9c875eb66af19ae4f358f8d/src/templates/basic.ts#L52) and TSDX itself uses `tsdx lint` with [a config](https://github.com/formium/tsdx/blob/08a8ef807cd708c1b9c875eb66af19ae4f358f8d/package.json#L134)
