### ISSUE TITLE
Does not work in mixed TS/JS codebase

### ISSUE THREAD

**Issue by arvigeus** [formium/tsdx#857]
### Current Behavior

Trying to compile app that contains both `.tsx` and `.js` React components

### Expected behavior

Compile

### Suggested solution(s)

Hmmm, maybe the config is missing something?

### Additional context

Repo: https://github.com/arvigeus/tsdx-ts-js

### Your environment

```text
  System:
    OS: Linux 5.4 Pop!_OS 20.04 LTS
    CPU: (4) x64 Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
    Memory: 7.90 GB / 15.58 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    npm: 6.14.4 - /usr/bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Firefox: 80.0.1
  npmPackages:
    tsdx: ^0.13.3 => 0.13.3 
    typescript: ^4.0.2 => 4.0.2 

```

**Comment by agilgur5** [comment]
There's code specifically written for this as well as tests. You didn't provide any error message here and the repo you linked 404s...

React components should be `.jsx` is the only thing I could make a guess at...

**Comment by arvigeus** [comment]
Sorry, I set wrong permission to the repo. It complains about missing babel preset react (which is odd). After including it it was fine.

**Comment by agilgur5** [comment]
Ok. Yea `@babel/preset-react` shouldn't be necessary if you use the `.jsx` as I mentioned. There's [a test](https://github.com/formium/tsdx/blob/08a8ef807cd708c1b9c875eb66af19ae4f358f8d/test/e2e/fixtures/build-default/src/syntax/jsx-import/) for that.
With plain `.js`, TS does not transpile any JSX. This is the same behavior it has for `.ts` vs `.tsx` and isn't specific to TSDX.

Also mentioned in https://github.com/formium/tsdx/issues/710#issuecomment-624413332 and https://github.com/formium/tsdx/issues/443#issuecomment-638856008.

**Comment by benjaminsuch** [comment]
> Ok. Yea `@babel/preset-react` shouldn't be necessary if you use the `.jsx` extension as I mentioned. There's [a test](https://github.com/formium/tsdx/blob/08a8ef807cd708c1b9c875eb66af19ae4f358f8d/test/e2e/fixtures/build-default/src/syntax/jsx-import/) for that.
> With plain `.js`, TS does not transpile any JSX. This is the same behavior it has for `.ts` vs `.tsx` and isn't specific to TSDX.
> 
> Also mentioned in [#710 (comment)](https://github.com/formium/tsdx/issues/710#issuecomment-624413332) and [#443 (comment)](https://github.com/formium/tsdx/issues/443#issuecomment-638856008).

The issue still persist. The test doesn't cover JSX just a string. Using `.jsx` extension and JSX does not work as you get `Support for the experimental syntax 'jsx' isn't currently enabled (3:19):`. The test should include a basic JSX usage like `<div>foobar</div>`.
