### ISSUE TITLE
Duplicate versions of React error when installing package locally

### ISSUE THREAD

**Issue by yuschick** [formium/tsdx#861]
### Current Behavior
Currently, I am working within a monorepo. In it are two sibling directories:

- Main App
- TSDX Package

The TSDX Package will ultimately be exporting several custom hooks while in Main App I am installing it like this:

*package.json*
````
"dependencies": {
...
tsdx-package: "file:../tsdx-package",
...
}
````
Once I install the package into Main App and I start it up locally, I receive the error:

````
×
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
````
I have verified that the error is `#3` by running `npm ls react` in Main App and seeing that TSDX Package is running an extraneous verison of react.

However, I have react and react-dom listed as peer dependencies in my TSDX package.

````
"peerDependencies": {
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  },
"dependencies": {
    "@types/node": "^14.10.2",
    "axios": "^0.20.0",
    "react-query": "^2.15.4"
  },
 "devDependencies": {
    "@types/react": "^16.9.49",
    "@types/react-dom": "^16.9.8",
    "husky": "^4.3.0",
    "tsdx": "^0.13.3",
    "tslib": "^2.0.1",
    "typescript": "^4.0.2"
  },
````
I don't have it listed in devDependencies because I don't need to run TSDX Package by itself. I will only ever need to test it within Main App.

Yet despite this setup and a day of looking at this, I am lost and really need some help. The TSDX Package will need to be a dependency in production so I don't think npm link will help. But really at a wall and hoping to get some help.

### Expected behavior

I am expecting to be able to install TSDX Package locally in Main App so I can run it locally and deploy it, ultimately, to production.

### Suggested solution(s)

*shrug*

### Your environment

```text
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 71.63 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.6.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Firefox: 79.0
    Safari: 13.1.2
  npmPackages:
    tsdx: ^0.13.3 => 0.13.3
    typescript: ^4.0.2 => 4.0.2
  npmGlobalPackages:
    typescript: 4.0.2
```

**Comment by agilgur5** [comment]
Sorry to hear about your troubles, but unfortunately this is unrelated to TSDX. TSDX is a devDep and does not have a dependency on React in any case.

Issues also are _not_ a support forum for debugging help. Feel free to use StackOverflow or something, but even there the expectation is that you [furnish an MVCE](https://stackoverflow.com/help/minimal-reproducible-example), which is quite lacking here. For instance, you mention using `npm ls react` but you didn't provide the output of that which would be pretty critical insight.

If you're sure you don't have a duplicate being used or installed anywhere, I'd recommend resetting your `node_modules`, but I doubt that would resolve anything. But again, this is not a support for debugging help, especially not for issues unrelated to TSDX.
