### ISSUE TITLE
Use "base" tsconfig with overrides when neccessary?

### ISSUE THREAD

**Issue by ArturBaybulatov** [formium/tsdx#901]
https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#tsconfig-bases

**Comment by agilgur5** [comment]
Please don't remove the issue template, it is there for a reason.

This sounds like a duplicate of #634 / #753 . Given the removal of the template and lack of details, it is difficult to interpret if you meant use an existing base, e.g. `@tsconfig/recommended` or for TSDX to have its own base, i.e. `@tsdx/tsconfig`. Per the linked issues, I plan to have `@tsdx/tsconfig` that all the templates will extend. It will itself extend `@tsconfig/recommended`.
`@tsconfig/recommended` is itself only a few settings and isn't currently commented well, so I don't think changing to that in isolation (without `@tsdx/tsconfig`) is worthwhile. I actually wrote the code for that but decided against it and to wait until `@tsdx/tsconfig` exists, especially as that will make for a more intuitive dependency structure.
